# Generated by Django 3.1.7 on 2021-08-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255, unique=True)),
                ('uic_number', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=255)),
                ('countery_for_apply', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_fees', models.IntegerField(blank=True, null=True)),
                ('estimate_compleation_date', models.DateField(blank=True, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=255)),
                ('countery_for_apply', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('mobile_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('lead_date', models.DateTimeField(auto_now_add=True)),
                ('succeed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.application')),
            ],
        ),
    ]
