# Generated by Django 3.1.7 on 2021-08-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210818_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='succeed',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
